'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { 
  UserCheck, UserPlus, Lock, User, ArrowRight, KeyRound, AlertCircle, 
  Sparkles, GraduationCap, Briefcase, Camera, Upload, CheckCircle2, Loader2, RefreshCw, X, Eye, EyeOff
} from 'lucide-react';
import { useToast } from '@/context/ToastContext';

interface ModuleLoginCardProps {
  moduleId?: string;
  title?: string;
  subtitle?: string;
  defaultRedirect?: string;
  themeColor?: 'indigo' | 'purple' | 'emerald' | 'rose';
}

export default function ModuleLoginCard({
  moduleId = 'sms',
  title = 'Module Login Gateway',
  subtitle = 'Scoped Access & Biometric Authentication System',
  defaultRedirect = '/sms',
  themeColor = 'indigo'
}: ModuleLoginCardProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { showToast } = useToast();

  const [tab, setTab] = useState<'LOGIN' | 'REGISTER'>('LOGIN');

  // Login State
  const [accountId, setAccountId] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loginLoading, setLoginLoading] = useState(false);
  const [loginError, setLoginError] = useState<string | null>(null);

  // Registration State
  const [role, setRole] = useState<'STUDENT' | 'TEACHER' | 'HOD' | 'SUB_TEACHER' | 'STAFF'>('STUDENT');
  const [userId, setUserId] = useState('');
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [regPassword, setRegPassword] = useState('');
  const [showRegPassword, setShowRegPassword] = useState(false);
  const [deptId, setDeptId] = useState('CSE');
  const [imageBase64, setImageBase64] = useState('');

  // Live Camera Capture State
  const [showLiveCam, setShowLiveCam] = useState(false);
  const regVideoRef = useRef<HTMLVideoElement | null>(null);
  const regCanvasRef = useRef<HTMLCanvasElement | null>(null);
  const regStreamRef = useRef<MediaStream | null>(null);

  // Student fields
  const [rollNumber, setRollNumber] = useState('');
  const [academicYear, setAcademicYear] = useState(1);
  const [section, setSection] = useState('A');
  const [parentName, setParentName] = useState('');
  const [parentContact, setParentContact] = useState('');
  const [guardianName, setGuardianName] = useState('');
  const [guardianContact, setGuardianContact] = useState('');

  // Faculty fields
  const [designation, setDesignation] = useState('Assistant Professor');
  const [specialization, setSpecialization] = useState('Computer Science');

  const [regLoading, setRegLoading] = useState(false);
  const [regError, setRegError] = useState<string | null>(null);
  const [regSuccess, setRegSuccess] = useState<string | null>(null);

  const fetchAutoGeneratedId = async (selectedRole: string) => {
    try {
      const host = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
      const res = await fetch(`http://${host}:8000/api/register/generate-id?role=${selectedRole}`);
      if (res.ok) {
        const data = await res.json();
        if (data.user_id) {
          setUserId(data.user_id);
          if (selectedRole === 'STUDENT') {
            setRollNumber(data.user_id);
          }
        }
      }
    } catch (e) {}
  };

  useEffect(() => {
    const tabParam = searchParams?.get('tab');
    if (tabParam === 'register') {
      setTab('REGISTER');
    }
  }, [searchParams]);

  useEffect(() => {
    if (tab === 'REGISTER') {
      fetchAutoGeneratedId(role);
    }
  }, [tab, role]);

  const stopRegCamera = () => {
    if (regStreamRef.current) {
      regStreamRef.current.getTracks().forEach(track => track.stop());
      regStreamRef.current = null;
    }
    if (regVideoRef.current) {
      regVideoRef.current.srcObject = null;
    }
    setShowLiveCam(false);
  };

  const startRegCamera = async () => {
    try {
      stopRegCamera();
      setShowLiveCam(true);

      const stream = await navigator.mediaDevices.getUserMedia({
        video: { width: { ideal: 640 }, height: { ideal: 480 }, facingMode: 'user' },
        audio: false
      });

      regStreamRef.current = stream;

      setTimeout(() => {
        if (regVideoRef.current) {
          regVideoRef.current.srcObject = stream;
          regVideoRef.current.play();
        }
      }, 200);

    } catch (err) {
      console.error("Camera error:", err);
      showToast("Could not access camera for live capture. Please enable permissions.", "error");
      setShowLiveCam(false);
    }
  };

  const snapLivePhoto = () => {
    if (!regVideoRef.current || !regCanvasRef.current) return;
    const video = regVideoRef.current;
    const canvas = regCanvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = video.videoWidth || 640;
    canvas.height = video.videoHeight || 480;
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

    const b64 = canvas.toDataURL('image/jpeg', 0.85);
    setImageBase64(b64);
    stopRegCamera();
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImageBase64(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (loginLoading) return;

    setLoginLoading(true);
    setLoginError(null);

    try {
      const host = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
      const res = await fetch(`http://${host}:8000/api/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          account_id_or_email: accountId,
          password: password,
          is_admin: false
        })
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.detail || "Authentication failed");
      }

      localStorage.setItem('multiutility_token', data.token);
      localStorage.setItem('multiutility_user', JSON.stringify(data.user));

      showToast(`Welcome back, ${data.user.name || accountId}!`, 'success', 'Login Successful');

      const redirectTarget = searchParams?.get('redirect') || defaultRedirect;
      router.push(redirectTarget);

    } catch (err: any) {
      const errMsg = err.message || "Invalid credentials.";
      setLoginError(errMsg);
      showToast(errMsg, 'error', 'Login Failed');
      setLoginLoading(false);
    }
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setRegLoading(true);
    setRegError(null);
    setRegSuccess(null);

    if (!userId || !name || !imageBase64) {
      const errMsg = "Please fill in User ID, Name, and capture/upload a face photo.";
      setRegError(errMsg);
      showToast(errMsg, 'warning');
      setRegLoading(false);
      return;
    }

    try {
      const host = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
      const res = await fetch(`http://${host}:8000/api/register/user`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id: userId,
          name,
          role,
          email,
          phone,
          password: regPassword,
          dept_id: deptId,
          image_base64: imageBase64,
          roll_number: rollNumber || userId,
          academic_year: Number(academicYear),
          section,
          parent_name: parentName,
          parent_contact: parentContact,
          guardian_name: guardianName,
          guardian_contact: guardianContact,
          designation,
          specialization
        })
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.detail || "Registration failed.");
      }

      const succMsg = `Registration successful for ${name} (${userId})!`;
      setRegSuccess(`${succMsg} Redirecting to Login...`);
      showToast(succMsg, 'success', 'Account Created');
      
      setTimeout(() => {
        setAccountId(userId);
        setPassword(regPassword || 'password');
        setTab('LOGIN');
        setRegSuccess(null);
      }, 1500);

    } catch (err: any) {
      const errMsg = err.message || "Registration failed.";
      setRegError(errMsg);
      showToast(errMsg, 'error', 'Registration Failed');
    } finally {
      setRegLoading(false);
    }
  };

  return (
    <div className="w-full max-w-xl glass-panel rounded-3xl p-8 border border-white/10 shadow-2xl relative z-10 mx-auto">
      <canvas ref={regCanvasRef} className="hidden" />

      {/* Top Header */}
      <div className="text-center mb-6">
        <div className="inline-flex p-3 rounded-2xl bg-gradient-to-tr from-indigo-600 to-purple-600 shadow-lg shadow-indigo-600/30 mb-3">
          <UserCheck className="w-6 h-6 text-white" />
        </div>
        <h2 className="text-2xl font-black text-white tracking-tight">{title}</h2>
        <p className="text-xs text-gray-400 mt-1">{subtitle}</p>
      </div>

      {/* Tab Selection */}
      <div className="grid grid-cols-2 gap-1.5 p-1 bg-dark-card/60 rounded-xl border border-white/5 mb-6">
        <button
          type="button"
          onClick={() => {
            stopRegCamera();
            setTab('LOGIN');
          }}
          className={`flex items-center justify-center gap-2 py-2.5 rounded-lg text-xs font-bold transition-all ${
            tab === 'LOGIN'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          <User className="w-4 h-4" />
          Module Login
        </button>
        
        <button
          type="button"
          onClick={() => setTab('REGISTER')}
          className={`flex items-center justify-center gap-2 py-2.5 rounded-lg text-xs font-bold transition-all ${
            tab === 'REGISTER'
              ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          <UserPlus className="w-4 h-4" />
          Self Register
        </button>
      </div>

      {/* Tab 1: Module Login Form */}
      {tab === 'LOGIN' ? (
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block text-xs font-semibold text-gray-300 mb-1">
              User ID, Roll Number, or Email
            </label>
            <div className="relative">
              <input
                type="text"
                required
                value={accountId}
                onChange={(e) => setAccountId(e.target.value)}
                placeholder="Enter User ID or Roll Number (e.g. STU-1001)"
                className="w-full pl-10 pr-4 py-2.5 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 font-mono"
              />
              <User className="w-4 h-4 text-gray-400 absolute left-3.5 top-3" />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-300 mb-1">Password</label>
            <div className="relative">
              <input
                type={showPassword ? 'text' : 'password'}
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter your account password"
                className="w-full pl-10 pr-10 py-2.5 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 font-mono"
              />
              <Lock className="w-4 h-4 text-gray-400 absolute left-3.5 top-3" />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3.5 top-3 text-gray-400 hover:text-gray-200 transition-colors"
                title={showPassword ? "Hide password" : "Show password"}
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <div className="flex items-center gap-2 p-2.5 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-[11px] text-indigo-300">
            <KeyRound className="w-4 h-4 text-indigo-400 flex-shrink-0" />
            <span>Default testing password is <strong className="text-white">password</strong></span>
          </div>

          {loginError && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-xs text-red-400">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <span>{loginError}</span>
            </div>
          )}

          <button
            type="submit"
            disabled={loginLoading}
            className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold rounded-xl text-xs shadow-lg shadow-indigo-600/30 transition-all hover:scale-[1.01] disabled:opacity-50"
          >
            {loginLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Authenticating User...</span>
              </>
            ) : (
              <>
                <span>Enter Workspace</span>
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>
        </form>
      ) : (
        /* Tab 2: Self Registration Form */
        <form onSubmit={handleRegister} className="space-y-4 animate-in fade-in duration-200">
          <div>
            <label className="block text-xs font-semibold text-gray-300 mb-1.5">Select Role</label>
            <div className="grid grid-cols-3 gap-2">
              {[
                { id: 'STUDENT', label: 'Student', icon: GraduationCap },
                { id: 'TEACHER', label: 'Teacher', icon: Briefcase },
                { id: 'HOD', label: 'HOD', icon: User },
              ].map((item) => {
                const Icon = item.icon;
                const active = role === item.id;
                return (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => setRole(item.id as any)}
                    className={`flex items-center justify-center gap-2 p-2.5 rounded-xl border text-xs font-semibold transition-all ${
                      active
                        ? 'bg-purple-600/30 border-purple-500 text-purple-300 shadow-md'
                        : 'bg-dark-card/50 border-white/5 text-gray-400 hover:text-gray-200'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {item.label}
                  </button>
                );
              })}
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-300 mb-1.5">Biometric Photo</label>
            
            {showLiveCam ? (
              <div className="relative rounded-2xl overflow-hidden bg-black border border-purple-500/50 shadow-xl aspect-video flex items-center justify-center">
                <video
                  ref={regVideoRef}
                  playsInline
                  muted
                  className="w-full h-full object-cover transform -scale-x-100"
                />
                <div className="absolute bottom-3 left-0 right-0 flex items-center justify-center gap-3">
                  <button
                    type="button"
                    onClick={snapLivePhoto}
                    className="flex items-center gap-2 px-5 py-2 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-full text-xs font-bold shadow-lg shadow-emerald-500/30 hover:scale-105 transition-all"
                  >
                    <Camera className="w-4 h-4" />
                    <span>Snap Photo Now</span>
                  </button>
                  <button
                    type="button"
                    onClick={stopRegCamera}
                    className="p-2 bg-gray-900/80 hover:bg-red-500/80 text-white rounded-full text-xs transition-all"
                    title="Cancel Live Camera"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-4">
                <div className="relative w-24 h-24 rounded-2xl overflow-hidden bg-gray-900 border border-white/10 flex items-center justify-center flex-shrink-0">
                  {imageBase64 ? (
                    <img src={imageBase64} alt="Face Snapshot" className="w-full h-full object-cover" />
                  ) : (
                    <Camera className="w-8 h-8 text-gray-600" />
                  )}
                </div>

                <div className="flex-1 space-y-2">
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      type="button"
                      onClick={startRegCamera}
                      className="flex items-center justify-center gap-1.5 px-3 py-2 bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/30 rounded-xl text-xs font-bold text-purple-300 transition-all"
                    >
                      <Camera className="w-3.5 h-3.5" />
                      <span>Capture Live</span>
                    </button>

                    <label className="flex items-center justify-center gap-1.5 px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold text-gray-300 cursor-pointer transition-all">
                      <Upload className="w-3.5 h-3.5 text-indigo-400" />
                      <span>Upload File</span>
                      <input type="file" accept="image/*" onChange={handleFileUpload} className="hidden" />
                    </label>
                  </div>
                  <p className="text-[11px] text-gray-400">Capture webcam snapshot OR upload front-facing photo.</p>
                </div>
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-xs font-semibold text-gray-300">
                  {role === 'STUDENT' ? 'System Roll Number *' : 'System Staff ID *'}
                </label>
                <button
                  type="button"
                  onClick={() => fetchAutoGeneratedId(role)}
                  className="text-[10px] text-purple-400 hover:text-purple-300 flex items-center gap-1 font-bold"
                >
                  <RefreshCw className="w-3 h-3" /> Auto-ID
                </button>
              </div>
              <input
                type="text"
                required
                value={userId}
                onChange={(e) => {
                  setUserId(e.target.value);
                  if (role === 'STUDENT') setRollNumber(e.target.value);
                }}
                placeholder={role === 'STUDENT' ? 'STU-504' : 'TCH-203'}
                className="w-full px-3.5 py-2 bg-dark-bg/60 border border-white/10 rounded-xl text-xs font-mono font-bold text-purple-300 focus:outline-none focus:border-purple-500"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-300 mb-1">Full Name *</label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Enter full name"
                className="w-full px-3.5 py-2 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white placeholder-gray-500 focus:outline-none focus:border-purple-500"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-300 mb-1">
              Password <span className="text-purple-400 font-normal">(Default: "password")</span>
            </label>
            <div className="relative">
              <input
                type={showRegPassword ? 'text' : 'password'}
                value={regPassword}
                onChange={(e) => setRegPassword(e.target.value)}
                placeholder="Set custom password or leave blank"
                className="w-full pl-10 pr-10 py-2 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 font-mono"
              />
              <Lock className="w-4 h-4 text-gray-400 absolute left-3.5 top-2.5" />
              <button
                type="button"
                onClick={() => setShowRegPassword(!showRegPassword)}
                className="absolute right-3.5 top-2.5 text-gray-400 hover:text-gray-200 transition-colors"
              >
                {showRegPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold text-gray-300 mb-1">Department</label>
              <select
                value={deptId}
                onChange={(e) => setDeptId(e.target.value)}
                className="w-full px-3.5 py-2 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white focus:outline-none focus:border-purple-500"
              >
                <option value="CSE">Computer Science & Eng (CSE)</option>
                <option value="ECE">Electronics & Comm (ECE)</option>
                <option value="MECH">Mechanical Eng (MECH)</option>
                <option value="CIVIL">Civil Eng (CIVIL)</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-300 mb-1">Email Address</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Enter email address"
                className="w-full px-3.5 py-2 bg-dark-bg/60 border border-white/10 rounded-xl text-xs text-white placeholder-gray-500 focus:outline-none focus:border-purple-500"
              />
            </div>
          </div>

          {regError && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-xs text-red-400">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <span>{regError}</span>
            </div>
          )}

          {regSuccess && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-400">
              <CheckCircle2 className="w-4 h-4 flex-shrink-0" />
              <span>{regSuccess}</span>
            </div>
          )}

          <button
            type="submit"
            disabled={regLoading}
            className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold rounded-xl text-xs shadow-lg shadow-purple-600/30 transition-all hover:scale-[1.01]"
          >
            {regLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Activating Biometrics & Saving...</span>
              </>
            ) : (
              <>
                <CheckCircle2 className="w-4 h-4" />
                <span>Register Account & Proceed</span>
              </>
            )}
          </button>
        </form>
      )}

    </div>
  );
}
